/*
 * This file was generated automatically by xsubpp version 1.9507 from the 
 * contents of DID.xs. Do not edit this file, edit DID.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "DID.xs"
/*
 * $Id: DID.xs,v 1.8 2000/09/11 05:27:40 kazuma-t Exp $
 *
 * written by T.Nakayama
 */
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "sufary.h"
#include "did.h"
#include "util.h"

#line 24 "DID.c"
XS(XS_DID_suf_opendid)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: DID::suf_opendid(s)");
    {
	char *	s = (char *)SvPV(ST(0),PL_na);
	DID *	RETVAL;
#line 21 "DID.xs"
	RETVAL = sa_open_did(s);
#line 35 "DID.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "DIDPtr", (void*)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_DID_suf_closedid)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: DID::suf_closedid(did)");
    {
	DID *	did;

	if (sv_derived_from(ST(0), "DIDPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    did = (DID *) tmp;
	}
	else
	    croak("did is not of type DIDPtr");
#line 29 "DID.xs"
	sa_close_did(did);
#line 58 "DID.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_DID_suf_didsearch)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: DID::suf_didsearch(did,tgt)");
    SP -= items;
    {
	DID *	did;
	off_t	tgt = (off_t)SvIV(ST(1));
#line 37 "DID.xs"
	DID_RESULT dr;
#line 74 "DID.c"

	if (sv_derived_from(ST(0), "DIDPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    did = (DID *) tmp;
	}
	else
	    croak("did is not of type DIDPtr");
#line 39 "DID.xs"
	dr = sa_didsearch(did, tgt);

	if (dr.stat == SUCCESS) {
		EXTEND(SP, 3);
		PUSHs(sv_2mortal(newSVnv(dr.no)));
		PUSHs(sv_2mortal(newSVnv(dr.start)));
		PUSHs(sv_2mortal(newSVnv(dr.size)));
	}
#line 91 "DID.c"
	PUTBACK;
	return;
    }
}

XS(XS_DID_suf_did_size)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: DID::suf_did_size(did)");
    {
	DID *	did;
	off_t	RETVAL;

	if (sv_derived_from(ST(0), "DIDPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    did = (DID *) tmp;
	}
	else
	    croak("did is not of type DIDPtr");
#line 53 "DID.xs"
	RETVAL = sa_get_did_size(did);
#line 114 "DID.c"
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_DID_suf_memory_leak_check)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: DID::suf_memory_leak_check()");
    {
	int	RETVAL;
#line 61 "DID.xs"
	RETVAL = sa_memory_leak_check();
#line 130 "DID.c"
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_DID)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXSproto("DID::suf_opendid", XS_DID_suf_opendid, file, "$");
        newXSproto("DID::suf_closedid", XS_DID_suf_closedid, file, "$");
        newXSproto("DID::suf_didsearch", XS_DID_suf_didsearch, file, "$$");
        newXSproto("DID::suf_did_size", XS_DID_suf_did_size, file, "$");
        newXSproto("DID::suf_memory_leak_check", XS_DID_suf_memory_leak_check, file, "");
    XSRETURN_YES;
}

